Repository kylekrieg/Node-Red-Contesting-Dashboard, pull requests merged in 2023-01, with the labels that each got.

#33 Config Page Redesign
  changelog.md
  flow.json
Labels: bug, feature-request, code cleanup

#46 Documentation for New Release
  INSTALL.md
  Manual_INSTALL.md
  README.md
  docs/MANUAL.md
  docs/announcements.JPG
  docs/backuprestore.JPG
  docs/calllookupengine.JPG
  docs/clusterlogincallsign.JPG
  docs/clustersoutput.JPG
  docs/contestconfiguration.JPG
  docs/databasereset.JPG
  docs/distancemeasurement.JPG
  docs/mapconfiguration.JPG
  docs/onlinescoreboard.JPG
  docs/opcompetitionsortby.JPG
  docs/qratecolorconfig.JPG
  docs/radionames.JPG
  pics/after_node_dependency.jpg
  pics/clone_project.jpg
  pics/http_clone.jpg
Labels: documentation

#48 v1.2.19 TTL Value fix for #47
  flow.json
  package.json
Labels: bug, configurations and resets

#49 v1.2.20 Fix RPI Tempature.
  flow.json
  package.json
Labels: bug, pi-stats

#56 Issue 53: was issue-50 addition of C/F choice for temperature units
  flow.json
  package.json
Labels: feature-request, configurations and resets, pi-stats
